# Generated by Django 4.1.5 on 2023-02-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('original_name', models.CharField(max_length=64)),
                ('buyable', models.BooleanField()),
                ('arrives_in', models.CharField(max_length=16, null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('original_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_link', models.TextField()),
                ('usage', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=128, null=True)),
                ('source', models.CharField(max_length=1, null=True)),
                ('updated_on', models.DateTimeField(null=True)),
                ('master_feed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simplefeed.feeds')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=512, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True)),
                ('original_name', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Param',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Param_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('action', models.CharField(max_length=64, null=True)),
                ('css_class', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, null=True, unique=True)),
                ('ean', models.CharField(max_length=16, null=True)),
                ('vat', models.DecimalField(decimal_places=0, default=21, max_digits=2, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('pur_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('rec_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(max_length=3, null=True)),
                ('visible', models.CharField(max_length=1, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('free_billing', models.BooleanField(null=True)),
                ('free_shipping', models.BooleanField(null=True)),
                ('name', models.CharField(max_length=128, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simplefeed.availabilities')),
            ],
        ),
        migrations.CreateModel(
            name='VariantParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_param', models.BooleanField()),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.param')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_update', to='simplefeed.variant')),
            ],
        ),
        migrations.CreateModel(
            name='Variant_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main', models.BooleanField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.image')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.variant')),
            ],
        ),
        migrations.AddField(
            model_name='variant',
            name='images',
            field=models.ManyToManyField(through='simplefeed.Variant_Image', to='simplefeed.image'),
        ),
        migrations.AddField(
            model_name='variant',
            name='mods',
            field=models.ManyToManyField(to='simplefeed.modifications'),
        ),
        migrations.AddField(
            model_name='variant',
            name='params',
            field=models.ManyToManyField(through='simplefeed.VariantParam', to='simplefeed.param'),
        ),
        migrations.CreateModel(
            name='Param_Names',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('original_name', models.CharField(max_length=128)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.feeds')),
            ],
        ),
        migrations.AddField(
            model_name='param',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.param_names'),
        ),
        migrations.AddField(
            model_name='param',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.param_values'),
        ),
        migrations.CreateModel(
            name='Common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemgroup_id', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128, null=True)),
                ('short_description', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('approved', models.BooleanField(default=True)),
                ('categories', models.ManyToManyField(to='simplefeed.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='simplefeed.manufacturers')),
                ('mods', models.ManyToManyField(to='simplefeed.modifications')),
                ('price_common', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='main_var', to='simplefeed.variant')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='supplied_product', to='simplefeed.feeds')),
                ('variants', models.ManyToManyField(related_name='product', to='simplefeed.variant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='simplefeed.rules'),
        ),
        migrations.AddField(
            model_name='category',
            name='original_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='original_child', to='simplefeed.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='pair_onto',
            field=models.ManyToManyField(to='simplefeed.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='simplefeed.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='simplefeed.feeds'),
        ),
        migrations.AddField(
            model_name='availabilities',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simplefeed.feeds'),
        ),
    ]
