# Generated by Django 4.1.5 on 2023-02-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantparam',
            name='param',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params_variants', to='simplefeed.param'),
        ),
        migrations.AlterField(
            model_name='variantparam',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_params', to='simplefeed.variant'),
        ),
    ]
