# Generated by Django 4.1.5 on 2023-02-25 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0002_alter_variantparam_param_alter_variantparam_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='original_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_child', to='simplefeed.category'),
        ),
    ]
