# Generated by Django 4.1.5 on 2023-04-27 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0004_alter_availabilities_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='simplefeed.rules'),
        ),
        migrations.AddField(
            model_name='variant',
            name='rulelock',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='modifications',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
