# Generated by Django 4.1.5 on 2023-04-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simplefeed', '0005_variant_rule_variant_rulelock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='original_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
